// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: examples/sudokuMsg.proto

package com.gavinshen.game.msg;

public final class SudokuMsg {
  private SudokuMsg() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  /**
   * <pre>
   *消息代码
   * </pre>
   *
   * Protobuf enum {@code msg.MsgCode}
   */
  public enum MsgCode
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <pre>
     * </pre>
     *
     * <code>USER_GET_CHESS_CMD = 0;</code>
     */
    USER_GET_CHESS_CMD(0),
    /**
     * <pre>
     * </pre>
     *
     * <code>USER_GET_CHESS_RESULT = 1;</code>
     */
    USER_GET_CHESS_RESULT(1),
    UNRECOGNIZED(-1),
    ;

    /**
     * <pre>
     * </pre>
     *
     * <code>USER_GET_CHESS_CMD = 0;</code>
     */
    public static final int USER_GET_CHESS_CMD_VALUE = 0;
    /**
     * <pre>
     * </pre>
     *
     * <code>USER_GET_CHESS_RESULT = 1;</code>
     */
    public static final int USER_GET_CHESS_RESULT_VALUE = 1;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @Deprecated
    public static MsgCode valueOf(int value) {
      return forNumber(value);
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     */
    public static MsgCode forNumber(int value) {
      switch (value) {
        case 0: return USER_GET_CHESS_CMD;
        case 1: return USER_GET_CHESS_RESULT;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<MsgCode>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        MsgCode> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<MsgCode>() {
            public MsgCode findValueByNumber(int number) {
              return MsgCode.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      if (this == UNRECOGNIZED) {
        throw new IllegalStateException(
            "Can't get the descriptor of an unrecognized enum value.");
      }
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return SudokuMsg.getDescriptor().getEnumTypes().get(0);
    }

    private static final MsgCode[] VALUES = values();

    public static MsgCode valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private MsgCode(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:msg.MsgCode)
  }

  /**
   * <pre>
   *游戏难度
   * </pre>
   *
   * Protobuf enum {@code msg.ChallengeLevel}
   */
  public enum ChallengeLevel
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>SIMPLE = 0;</code>
     */
    SIMPLE(0),
    /**
     * <code>MEDIUM = 1;</code>
     */
    MEDIUM(1),
    /**
     * <code>DIFFICULTY = 2;</code>
     */
    DIFFICULTY(2),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>SIMPLE = 0;</code>
     */
    public static final int SIMPLE_VALUE = 0;
    /**
     * <code>MEDIUM = 1;</code>
     */
    public static final int MEDIUM_VALUE = 1;
    /**
     * <code>DIFFICULTY = 2;</code>
     */
    public static final int DIFFICULTY_VALUE = 2;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @Deprecated
    public static ChallengeLevel valueOf(int value) {
      return forNumber(value);
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     */
    public static ChallengeLevel forNumber(int value) {
      switch (value) {
        case 0: return SIMPLE;
        case 1: return MEDIUM;
        case 2: return DIFFICULTY;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<ChallengeLevel>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        ChallengeLevel> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<ChallengeLevel>() {
            public ChallengeLevel findValueByNumber(int number) {
              return ChallengeLevel.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      if (this == UNRECOGNIZED) {
        throw new IllegalStateException(
            "Can't get the descriptor of an unrecognized enum value.");
      }
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return SudokuMsg.getDescriptor().getEnumTypes().get(1);
    }

    private static final ChallengeLevel[] VALUES = values();

    public static ChallengeLevel valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private ChallengeLevel(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:msg.ChallengeLevel)
  }

  public interface UserGetChessCmdOrBuilder extends
      // @@protoc_insertion_point(interface_extends:msg.UserGetChessCmd)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     *用户Id
     * </pre>
     *
     * <code>uint32 userId = 1;</code>
     * @return The userId.
     */
    int getUserId();

    /**
     * <pre>
     *棋盘阶数
     * </pre>
     *
     * <code>uint32 orderNum = 2;</code>
     * @return The orderNum.
     */
    int getOrderNum();

    /**
     * <pre>
     *游戏难度
     * </pre>
     *
     * <code>.msg.ChallengeLevel challLevel = 3;</code>
     * @return The enum numeric value on the wire for challLevel.
     */
    int getChallLevelValue();
    /**
     * <pre>
     *游戏难度
     * </pre>
     *
     * <code>.msg.ChallengeLevel challLevel = 3;</code>
     * @return The challLevel.
     */
    ChallengeLevel getChallLevel();
  }
  /**
   * <pre>
   * 
   * 获取棋盘
   * /////////////////////////////////////////////////////////////////////
   * 指令
   * </pre>
   *
   * Protobuf type {@code msg.UserGetChessCmd}
   */
  public static final class UserGetChessCmd extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:msg.UserGetChessCmd)
      UserGetChessCmdOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use UserGetChessCmd.newBuilder() to construct.
    private UserGetChessCmd(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private UserGetChessCmd() {
      challLevel_ = 0;
    }

    @Override
    @SuppressWarnings({"unused"})
    protected Object newInstance(
        UnusedPrivateParameter unused) {
      return new UserGetChessCmd();
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private UserGetChessCmd(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              userId_ = input.readUInt32();
              break;
            }
            case 16: {

              orderNum_ = input.readUInt32();
              break;
            }
            case 24: {
              int rawValue = input.readEnum();

              challLevel_ = rawValue;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return SudokuMsg.internal_static_msg_UserGetChessCmd_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return SudokuMsg.internal_static_msg_UserGetChessCmd_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              UserGetChessCmd.class, Builder.class);
    }

    public static final int USERID_FIELD_NUMBER = 1;
    private int userId_;
    /**
     * <pre>
     *用户Id
     * </pre>
     *
     * <code>uint32 userId = 1;</code>
     * @return The userId.
     */
    @Override
    public int getUserId() {
      return userId_;
    }

    public static final int ORDERNUM_FIELD_NUMBER = 2;
    private int orderNum_;
    /**
     * <pre>
     *棋盘阶数
     * </pre>
     *
     * <code>uint32 orderNum = 2;</code>
     * @return The orderNum.
     */
    @Override
    public int getOrderNum() {
      return orderNum_;
    }

    public static final int CHALLLEVEL_FIELD_NUMBER = 3;
    private int challLevel_;
    /**
     * <pre>
     *游戏难度
     * </pre>
     *
     * <code>.msg.ChallengeLevel challLevel = 3;</code>
     * @return The enum numeric value on the wire for challLevel.
     */
    @Override public int getChallLevelValue() {
      return challLevel_;
    }
    /**
     * <pre>
     *游戏难度
     * </pre>
     *
     * <code>.msg.ChallengeLevel challLevel = 3;</code>
     * @return The challLevel.
     */
    @Override public ChallengeLevel getChallLevel() {
      @SuppressWarnings("deprecation")
      ChallengeLevel result = ChallengeLevel.valueOf(challLevel_);
      return result == null ? ChallengeLevel.UNRECOGNIZED : result;
    }

    private byte memoizedIsInitialized = -1;
    @Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (userId_ != 0) {
        output.writeUInt32(1, userId_);
      }
      if (orderNum_ != 0) {
        output.writeUInt32(2, orderNum_);
      }
      if (challLevel_ != ChallengeLevel.SIMPLE.getNumber()) {
        output.writeEnum(3, challLevel_);
      }
      unknownFields.writeTo(output);
    }

    @Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (userId_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(1, userId_);
      }
      if (orderNum_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(2, orderNum_);
      }
      if (challLevel_ != ChallengeLevel.SIMPLE.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(3, challLevel_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof UserGetChessCmd)) {
        return super.equals(obj);
      }
      UserGetChessCmd other = (UserGetChessCmd) obj;

      if (getUserId()
          != other.getUserId()) return false;
      if (getOrderNum()
          != other.getOrderNum()) return false;
      if (challLevel_ != other.challLevel_) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + USERID_FIELD_NUMBER;
      hash = (53 * hash) + getUserId();
      hash = (37 * hash) + ORDERNUM_FIELD_NUMBER;
      hash = (53 * hash) + getOrderNum();
      hash = (37 * hash) + CHALLLEVEL_FIELD_NUMBER;
      hash = (53 * hash) + challLevel_;
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static UserGetChessCmd parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static UserGetChessCmd parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static UserGetChessCmd parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static UserGetChessCmd parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static UserGetChessCmd parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static UserGetChessCmd parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static UserGetChessCmd parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static UserGetChessCmd parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static UserGetChessCmd parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static UserGetChessCmd parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static UserGetChessCmd parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static UserGetChessCmd parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(UserGetChessCmd prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * 
     * 获取棋盘
     * /////////////////////////////////////////////////////////////////////
     * 指令
     * </pre>
     *
     * Protobuf type {@code msg.UserGetChessCmd}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:msg.UserGetChessCmd)
        UserGetChessCmdOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return SudokuMsg.internal_static_msg_UserGetChessCmd_descriptor;
      }

      @Override
      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return SudokuMsg.internal_static_msg_UserGetChessCmd_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                UserGetChessCmd.class, Builder.class);
      }

      // Construct using com.gavinshen.game.msg.SudokuMsg.UserGetChessCmd.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @Override
      public Builder clear() {
        super.clear();
        userId_ = 0;

        orderNum_ = 0;

        challLevel_ = 0;

        return this;
      }

      @Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return SudokuMsg.internal_static_msg_UserGetChessCmd_descriptor;
      }

      @Override
      public UserGetChessCmd getDefaultInstanceForType() {
        return UserGetChessCmd.getDefaultInstance();
      }

      @Override
      public UserGetChessCmd build() {
        UserGetChessCmd result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @Override
      public UserGetChessCmd buildPartial() {
        UserGetChessCmd result = new UserGetChessCmd(this);
        result.userId_ = userId_;
        result.orderNum_ = orderNum_;
        result.challLevel_ = challLevel_;
        onBuilt();
        return result;
      }

      @Override
      public Builder clone() {
        return super.clone();
      }
      @Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.setField(field, value);
      }
      @Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.addRepeatedField(field, value);
      }
      @Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof UserGetChessCmd) {
          return mergeFrom((UserGetChessCmd)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(UserGetChessCmd other) {
        if (other == UserGetChessCmd.getDefaultInstance()) return this;
        if (other.getUserId() != 0) {
          setUserId(other.getUserId());
        }
        if (other.getOrderNum() != 0) {
          setOrderNum(other.getOrderNum());
        }
        if (other.challLevel_ != 0) {
          setChallLevelValue(other.getChallLevelValue());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @Override
      public final boolean isInitialized() {
        return true;
      }

      @Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        UserGetChessCmd parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (UserGetChessCmd) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int userId_ ;
      /**
       * <pre>
       *用户Id
       * </pre>
       *
       * <code>uint32 userId = 1;</code>
       * @return The userId.
       */
      @Override
      public int getUserId() {
        return userId_;
      }
      /**
       * <pre>
       *用户Id
       * </pre>
       *
       * <code>uint32 userId = 1;</code>
       * @param value The userId to set.
       * @return This builder for chaining.
       */
      public Builder setUserId(int value) {
        
        userId_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *用户Id
       * </pre>
       *
       * <code>uint32 userId = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearUserId() {
        
        userId_ = 0;
        onChanged();
        return this;
      }

      private int orderNum_ ;
      /**
       * <pre>
       *棋盘阶数
       * </pre>
       *
       * <code>uint32 orderNum = 2;</code>
       * @return The orderNum.
       */
      @Override
      public int getOrderNum() {
        return orderNum_;
      }
      /**
       * <pre>
       *棋盘阶数
       * </pre>
       *
       * <code>uint32 orderNum = 2;</code>
       * @param value The orderNum to set.
       * @return This builder for chaining.
       */
      public Builder setOrderNum(int value) {
        
        orderNum_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *棋盘阶数
       * </pre>
       *
       * <code>uint32 orderNum = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearOrderNum() {
        
        orderNum_ = 0;
        onChanged();
        return this;
      }

      private int challLevel_ = 0;
      /**
       * <pre>
       *游戏难度
       * </pre>
       *
       * <code>.msg.ChallengeLevel challLevel = 3;</code>
       * @return The enum numeric value on the wire for challLevel.
       */
      @Override public int getChallLevelValue() {
        return challLevel_;
      }
      /**
       * <pre>
       *游戏难度
       * </pre>
       *
       * <code>.msg.ChallengeLevel challLevel = 3;</code>
       * @param value The enum numeric value on the wire for challLevel to set.
       * @return This builder for chaining.
       */
      public Builder setChallLevelValue(int value) {
        
        challLevel_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *游戏难度
       * </pre>
       *
       * <code>.msg.ChallengeLevel challLevel = 3;</code>
       * @return The challLevel.
       */
      @Override
      public ChallengeLevel getChallLevel() {
        @SuppressWarnings("deprecation")
        ChallengeLevel result = ChallengeLevel.valueOf(challLevel_);
        return result == null ? ChallengeLevel.UNRECOGNIZED : result;
      }
      /**
       * <pre>
       *游戏难度
       * </pre>
       *
       * <code>.msg.ChallengeLevel challLevel = 3;</code>
       * @param value The challLevel to set.
       * @return This builder for chaining.
       */
      public Builder setChallLevel(ChallengeLevel value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        challLevel_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *游戏难度
       * </pre>
       *
       * <code>.msg.ChallengeLevel challLevel = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearChallLevel() {
        
        challLevel_ = 0;
        onChanged();
        return this;
      }
      @Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:msg.UserGetChessCmd)
    }

    // @@protoc_insertion_point(class_scope:msg.UserGetChessCmd)
    private static final UserGetChessCmd DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new UserGetChessCmd();
    }

    public static UserGetChessCmd getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<UserGetChessCmd>
        PARSER = new com.google.protobuf.AbstractParser<UserGetChessCmd>() {
      @Override
      public UserGetChessCmd parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new UserGetChessCmd(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<UserGetChessCmd> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<UserGetChessCmd> getParserForType() {
      return PARSER;
    }

    @Override
    public UserGetChessCmd getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface UserGetChessResultOrBuilder extends
      // @@protoc_insertion_point(interface_extends:msg.UserGetChessResult)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     *用户Id
     * </pre>
     *
     * <code>uint32 userId = 1;</code>
     * @return The userId.
     */
    int getUserId();

    /**
     * <pre>
     *棋盘列表
     * </pre>
     *
     * <code>repeated uint32 chessArray = 2;</code>
     * @return A list containing the chessArray.
     */
    java.util.List<Integer> getChessArrayList();
    /**
     * <pre>
     *棋盘列表
     * </pre>
     *
     * <code>repeated uint32 chessArray = 2;</code>
     * @return The count of chessArray.
     */
    int getChessArrayCount();
    /**
     * <pre>
     *棋盘列表
     * </pre>
     *
     * <code>repeated uint32 chessArray = 2;</code>
     * @param index The index of the element to return.
     * @return The chessArray at the given index.
     */
    int getChessArray(int index);
  }
  /**
   * <pre>
   *结果
   * </pre>
   *
   * Protobuf type {@code msg.UserGetChessResult}
   */
  public static final class UserGetChessResult extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:msg.UserGetChessResult)
      UserGetChessResultOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use UserGetChessResult.newBuilder() to construct.
    private UserGetChessResult(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private UserGetChessResult() {
      chessArray_ = emptyIntList();
    }

    @Override
    @SuppressWarnings({"unused"})
    protected Object newInstance(
        UnusedPrivateParameter unused) {
      return new UserGetChessResult();
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private UserGetChessResult(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              userId_ = input.readUInt32();
              break;
            }
            case 16: {
              if (!((mutable_bitField0_ & 0x00000001) != 0)) {
                chessArray_ = newIntList();
                mutable_bitField0_ |= 0x00000001;
              }
              chessArray_.addInt(input.readUInt32());
              break;
            }
            case 18: {
              int length = input.readRawVarint32();
              int limit = input.pushLimit(length);
              if (!((mutable_bitField0_ & 0x00000001) != 0) && input.getBytesUntilLimit() > 0) {
                chessArray_ = newIntList();
                mutable_bitField0_ |= 0x00000001;
              }
              while (input.getBytesUntilLimit() > 0) {
                chessArray_.addInt(input.readUInt32());
              }
              input.popLimit(limit);
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) != 0)) {
          chessArray_.makeImmutable(); // C
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return SudokuMsg.internal_static_msg_UserGetChessResult_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return SudokuMsg.internal_static_msg_UserGetChessResult_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              UserGetChessResult.class, Builder.class);
    }

    public static final int USERID_FIELD_NUMBER = 1;
    private int userId_;
    /**
     * <pre>
     *用户Id
     * </pre>
     *
     * <code>uint32 userId = 1;</code>
     * @return The userId.
     */
    @Override
    public int getUserId() {
      return userId_;
    }

    public static final int CHESSARRAY_FIELD_NUMBER = 2;
    private com.google.protobuf.Internal.IntList chessArray_;
    /**
     * <pre>
     *棋盘列表
     * </pre>
     *
     * <code>repeated uint32 chessArray = 2;</code>
     * @return A list containing the chessArray.
     */
    @Override
    public java.util.List<Integer>
        getChessArrayList() {
      return chessArray_;
    }
    /**
     * <pre>
     *棋盘列表
     * </pre>
     *
     * <code>repeated uint32 chessArray = 2;</code>
     * @return The count of chessArray.
     */
    public int getChessArrayCount() {
      return chessArray_.size();
    }
    /**
     * <pre>
     *棋盘列表
     * </pre>
     *
     * <code>repeated uint32 chessArray = 2;</code>
     * @param index The index of the element to return.
     * @return The chessArray at the given index.
     */
    public int getChessArray(int index) {
      return chessArray_.getInt(index);
    }
    private int chessArrayMemoizedSerializedSize = -1;

    private byte memoizedIsInitialized = -1;
    @Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (userId_ != 0) {
        output.writeUInt32(1, userId_);
      }
      if (getChessArrayList().size() > 0) {
        output.writeUInt32NoTag(18);
        output.writeUInt32NoTag(chessArrayMemoizedSerializedSize);
      }
      for (int i = 0; i < chessArray_.size(); i++) {
        output.writeUInt32NoTag(chessArray_.getInt(i));
      }
      unknownFields.writeTo(output);
    }

    @Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (userId_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(1, userId_);
      }
      {
        int dataSize = 0;
        for (int i = 0; i < chessArray_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeUInt32SizeNoTag(chessArray_.getInt(i));
        }
        size += dataSize;
        if (!getChessArrayList().isEmpty()) {
          size += 1;
          size += com.google.protobuf.CodedOutputStream
              .computeInt32SizeNoTag(dataSize);
        }
        chessArrayMemoizedSerializedSize = dataSize;
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof UserGetChessResult)) {
        return super.equals(obj);
      }
      UserGetChessResult other = (UserGetChessResult) obj;

      if (getUserId()
          != other.getUserId()) return false;
      if (!getChessArrayList()
          .equals(other.getChessArrayList())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + USERID_FIELD_NUMBER;
      hash = (53 * hash) + getUserId();
      if (getChessArrayCount() > 0) {
        hash = (37 * hash) + CHESSARRAY_FIELD_NUMBER;
        hash = (53 * hash) + getChessArrayList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static UserGetChessResult parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static UserGetChessResult parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static UserGetChessResult parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static UserGetChessResult parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static UserGetChessResult parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static UserGetChessResult parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static UserGetChessResult parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static UserGetChessResult parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static UserGetChessResult parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static UserGetChessResult parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static UserGetChessResult parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static UserGetChessResult parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(UserGetChessResult prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     *结果
     * </pre>
     *
     * Protobuf type {@code msg.UserGetChessResult}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:msg.UserGetChessResult)
        UserGetChessResultOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return SudokuMsg.internal_static_msg_UserGetChessResult_descriptor;
      }

      @Override
      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return SudokuMsg.internal_static_msg_UserGetChessResult_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                UserGetChessResult.class, Builder.class);
      }

      // Construct using com.gavinshen.game.msg.SudokuMsg.UserGetChessResult.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @Override
      public Builder clear() {
        super.clear();
        userId_ = 0;

        chessArray_ = emptyIntList();
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      @Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return SudokuMsg.internal_static_msg_UserGetChessResult_descriptor;
      }

      @Override
      public UserGetChessResult getDefaultInstanceForType() {
        return UserGetChessResult.getDefaultInstance();
      }

      @Override
      public UserGetChessResult build() {
        UserGetChessResult result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @Override
      public UserGetChessResult buildPartial() {
        UserGetChessResult result = new UserGetChessResult(this);
        int from_bitField0_ = bitField0_;
        result.userId_ = userId_;
        if (((bitField0_ & 0x00000001) != 0)) {
          chessArray_.makeImmutable();
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.chessArray_ = chessArray_;
        onBuilt();
        return result;
      }

      @Override
      public Builder clone() {
        return super.clone();
      }
      @Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.setField(field, value);
      }
      @Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.addRepeatedField(field, value);
      }
      @Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof UserGetChessResult) {
          return mergeFrom((UserGetChessResult)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(UserGetChessResult other) {
        if (other == UserGetChessResult.getDefaultInstance()) return this;
        if (other.getUserId() != 0) {
          setUserId(other.getUserId());
        }
        if (!other.chessArray_.isEmpty()) {
          if (chessArray_.isEmpty()) {
            chessArray_ = other.chessArray_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureChessArrayIsMutable();
            chessArray_.addAll(other.chessArray_);
          }
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @Override
      public final boolean isInitialized() {
        return true;
      }

      @Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        UserGetChessResult parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (UserGetChessResult) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int userId_ ;
      /**
       * <pre>
       *用户Id
       * </pre>
       *
       * <code>uint32 userId = 1;</code>
       * @return The userId.
       */
      @Override
      public int getUserId() {
        return userId_;
      }
      /**
       * <pre>
       *用户Id
       * </pre>
       *
       * <code>uint32 userId = 1;</code>
       * @param value The userId to set.
       * @return This builder for chaining.
       */
      public Builder setUserId(int value) {
        
        userId_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *用户Id
       * </pre>
       *
       * <code>uint32 userId = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearUserId() {
        
        userId_ = 0;
        onChanged();
        return this;
      }

      private com.google.protobuf.Internal.IntList chessArray_ = emptyIntList();
      private void ensureChessArrayIsMutable() {
        if (!((bitField0_ & 0x00000001) != 0)) {
          chessArray_ = mutableCopy(chessArray_);
          bitField0_ |= 0x00000001;
         }
      }
      /**
       * <pre>
       *棋盘列表
       * </pre>
       *
       * <code>repeated uint32 chessArray = 2;</code>
       * @return A list containing the chessArray.
       */
      public java.util.List<Integer>
          getChessArrayList() {
        return ((bitField0_ & 0x00000001) != 0) ?
                 java.util.Collections.unmodifiableList(chessArray_) : chessArray_;
      }
      /**
       * <pre>
       *棋盘列表
       * </pre>
       *
       * <code>repeated uint32 chessArray = 2;</code>
       * @return The count of chessArray.
       */
      public int getChessArrayCount() {
        return chessArray_.size();
      }
      /**
       * <pre>
       *棋盘列表
       * </pre>
       *
       * <code>repeated uint32 chessArray = 2;</code>
       * @param index The index of the element to return.
       * @return The chessArray at the given index.
       */
      public int getChessArray(int index) {
        return chessArray_.getInt(index);
      }
      /**
       * <pre>
       *棋盘列表
       * </pre>
       *
       * <code>repeated uint32 chessArray = 2;</code>
       * @param index The index to set the value at.
       * @param value The chessArray to set.
       * @return This builder for chaining.
       */
      public Builder setChessArray(
          int index, int value) {
        ensureChessArrayIsMutable();
        chessArray_.setInt(index, value);
        onChanged();
        return this;
      }
      /**
       * <pre>
       *棋盘列表
       * </pre>
       *
       * <code>repeated uint32 chessArray = 2;</code>
       * @param value The chessArray to add.
       * @return This builder for chaining.
       */
      public Builder addChessArray(int value) {
        ensureChessArrayIsMutable();
        chessArray_.addInt(value);
        onChanged();
        return this;
      }
      /**
       * <pre>
       *棋盘列表
       * </pre>
       *
       * <code>repeated uint32 chessArray = 2;</code>
       * @param values The chessArray to add.
       * @return This builder for chaining.
       */
      public Builder addAllChessArray(
          Iterable<? extends Integer> values) {
        ensureChessArrayIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, chessArray_);
        onChanged();
        return this;
      }
      /**
       * <pre>
       *棋盘列表
       * </pre>
       *
       * <code>repeated uint32 chessArray = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearChessArray() {
        chessArray_ = emptyIntList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      @Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:msg.UserGetChessResult)
    }

    // @@protoc_insertion_point(class_scope:msg.UserGetChessResult)
    private static final UserGetChessResult DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new UserGetChessResult();
    }

    public static UserGetChessResult getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<UserGetChessResult>
        PARSER = new com.google.protobuf.AbstractParser<UserGetChessResult>() {
      @Override
      public UserGetChessResult parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new UserGetChessResult(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<UserGetChessResult> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<UserGetChessResult> getParserForType() {
      return PARSER;
    }

    @Override
    public UserGetChessResult getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_msg_UserGetChessCmd_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_msg_UserGetChessCmd_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_msg_UserGetChessResult_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_msg_UserGetChessResult_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\030examples/sudokuMsg.proto\022\003msg\"\\\n\017UserG" +
      "etChessCmd\022\016\n\006userId\030\001 \001(\r\022\020\n\010orderNum\030\002" +
      " \001(\r\022\'\n\nchallLevel\030\003 \001(\0162\023.msg.Challenge" +
      "Level\"8\n\022UserGetChessResult\022\016\n\006userId\030\001 " +
      "\001(\r\022\022\n\nchessArray\030\002 \003(\r*<\n\007MsgCode\022\026\n\022US" +
      "ER_GET_CHESS_CMD\020\000\022\031\n\025USER_GET_CHESS_RES" +
      "ULT\020\001*8\n\016ChallengeLevel\022\n\n\006SIMPLE\020\000\022\n\n\006M" +
      "EDIUM\020\001\022\016\n\nDIFFICULTY\020\002B\030\n\026com.gavinshen" +
      ".game.msgb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_msg_UserGetChessCmd_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_msg_UserGetChessCmd_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_msg_UserGetChessCmd_descriptor,
        new String[] { "UserId", "OrderNum", "ChallLevel", });
    internal_static_msg_UserGetChessResult_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_msg_UserGetChessResult_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_msg_UserGetChessResult_descriptor,
        new String[] { "UserId", "ChessArray", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
